// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeGen.48ed8537-69e0-4f1c-9084-8d76ad861d2a";
        public const string Name = "Code Generator";
        public const string Description = @"Code Generation for Clean Architecture Project in .NET ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mizanuss Sayed";
        public const string Tags = "Code Gen";
    }
}
