// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "EasyPOS.CodeGen.48ed8537-69e0-4f1c-9084-8d76ad861d2a";
        public const string Name = "EasyPOS.CodeGen";
        public const string Description = @"Code Generation for Clean Architecture Project in .NET ";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Salman Farsy";
        public const string Tags = "EasyPOS.CodeGen";
    }
}
