// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EasyPOS.CodeGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "EasyPOS.CodeGen.c851b676-156a-434d-bfc4-525176e0953e";
        public const string Name = "EasyPOS.CodeGen";
        public const string Description = @"Code Generation for Clean Architecture Project in .NET ";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Salman Farsy";
        public const string Tags = "EasyPOS.CodeGen";
    }
}
