export class PrimengIcon{


  static primeIcons = [
    { label: 'Align Center', value: 'pi pi-align-center' },
    { label: 'Align Justify', value: 'pi pi-align-justify' },
    { label: 'Align Left', value: 'pi pi-align-left' },
    { label: 'Align Right', value: 'pi pi-align-right' },
    { label: 'Amazon', value: 'pi pi-amazon' },
    { label: 'Android', value: 'pi pi-android' },
    { label: 'Angle Double Down', value: 'pi pi-angle-double-down' },
    { label: 'Angle Double Left', value: 'pi pi-angle-double-left' },
    { label: 'Angle Double Right', value: 'pi pi-angle-double-right' },
    { label: 'Angle Double Up', value: 'pi pi-angle-double-up' },
    { label: 'Angle Down', value: 'pi pi-angle-down' },
    { label: 'Angle Left', value: 'pi pi-angle-left' },
    { label: 'Angle Right', value: 'pi pi-angle-right' },
    { label: 'Angle Up', value: 'pi pi-angle-up' },
    { label: 'Apple', value: 'pi pi-apple' },
    { label: 'Arrows Alt', value: 'pi pi-arrows-alt' },
    { label: 'Arrow Circle Down', value: 'pi pi-arrow-circle-down' },
    { label: 'Arrow Circle Left', value: 'pi pi-arrow-circle-left' },
    { label: 'Arrow Circle Right', value: 'pi pi-arrow-circle-right' },
    { label: 'Arrow Circle Up', value: 'pi pi-arrow-circle-up' },
    { label: 'Arrow Down', value: 'pi pi-arrow-down' },
    { label: 'Arrow Down Left', value: 'pi pi-arrow-down-left' },
    { label: 'Arrow Down Right', value: 'pi pi-arrow-down-right' },
    { label: 'Arrow Left', value: 'pi pi-arrow-left' },
    { label: 'Arrow Right Arrow Left', value: 'pi pi-arrow-right-arrow-left' },
    { label: 'Arrow Right', value: 'pi pi-arrow-right' },
    { label: 'Arrow Up', value: 'pi pi-arrow-up' },
    { label: 'Arrow Up Left', value: 'pi pi-arrow-up-left' },
    { label: 'Arrow Up Right', value: 'pi pi-arrow-up-right' },
    { label: 'Arrow Horizontal', value: 'pi pi-arrows-h' },
    { label: 'Arrow Vertical', value: 'pi pi-arrows-v' },
    { label: 'At', value: 'pi pi-at' },
    { label: 'Backward', value: 'pi pi-backward' },
    { label: 'Ban', value: 'pi pi-ban' },
    { label: 'Bars', value: 'pi pi-bars' },
    { label: 'Bell', value: 'pi pi-bell' },
    { label: 'Bitcoin', value: 'pi pi-bitcoin' },
    { label: 'Bolt', value: 'pi pi-bolt' },
    { label: 'Book', value: 'pi pi-book' },
    { label: 'Bookmark', value: 'pi pi-bookmark' },
    { label: 'Bookmark Fill', value: 'pi pi-bookmark-fill' },
    { label: 'Box', value: 'pi pi-box' },
    { label: 'Briefcase', value: 'pi pi-briefcase' },
    { label: 'Building', value: 'pi pi-building' },
    { label: 'Calculator', value: 'pi pi-calculator' },
    { label: 'Calendar', value: 'pi pi-calendar' },
    { label: 'Calendar Minus', value: 'pi pi-calendar-minus' },
    { label: 'Calendar Plus', value: 'pi pi-calendar-plus' },
    { label: 'Calendar Times', value: 'pi pi-calendar-times' },
    { label: 'Camera', value: 'pi pi-camera' },
    { label: 'Car', value: 'pi pi-car' },
    { label: 'Caret Down', value: 'pi pi-caret-down' },
    { label: 'Caret Left', value: 'pi pi-caret-left' },
    { label: 'Caret Right', value: 'pi pi-caret-right' },
    { label: 'Caret Up', value: 'pi pi-caret-up' },
    { label: 'Cart Plus', value: 'pi pi-cart-plus' },
    { label: 'Chart Bar', value: 'pi pi-chart-bar' },
    { label: 'Chart Line', value: 'pi pi-chart-line' },
    { label: 'Chart Pie', value: 'pi pi-chart-pie' },
    { label: 'Check', value: 'pi pi-check' },
    { label: 'Check Circle', value: 'pi pi-check-circle' },
    { label: 'Check Square', value: 'pi pi-check-square' },
    { label: 'Chevron Circle Down', value: 'pi pi-chevron-circle-down' },
    { label: 'Chevron Circle Left', value: 'pi pi-chevron-circle-left' },
    { label: 'Chevron Circle Right', value: 'pi pi-chevron-circle-right' },
    { label: 'Chevron Circle Up', value: 'pi pi-chevron-circle-up' },
    { label: 'Chevron Down', value: 'pi pi-chevron-down' },
    { label: 'Chevron Left', value: 'pi pi-chevron-left' },
    { label: 'Chevron Right', value: 'pi pi-chevron-right' },
    { label: 'Chevron Up', value: 'pi pi-chevron-up' },
    { label: 'Circle', value: 'pi pi-circle' },
    { label: 'Circle Fill', value: 'pi pi-circle-fill' },
    { label: 'Clock', value: 'pi pi-clock' },
    { label: 'Clone', value: 'pi pi-clone' },
    { label: 'Cloud', value: 'pi pi-cloud' },
    { label: 'Cloud Download', value: 'pi pi-cloud-download' },
    { label: 'Cloud Upload', value: 'pi pi-cloud-upload' },
    { label: 'Code', value: 'pi pi-code' },
    { label: 'Cog', value: 'pi pi-cog' },
    { label: 'Comment', value: 'pi pi-comment' },
    { label: 'Comments', value: 'pi pi-comments' },
    { label: 'Compass', value: 'pi pi-compass' },
    { label: 'Copy', value: 'pi pi-copy' },
    { label: 'Credit Card', value: 'pi pi-credit-card' },
    { label: 'Database', value: 'pi pi-database' },
    { label: 'Desktop', value: 'pi pi-desktop' },
    { label: 'Delete Left', value: 'pi pi-delete-left' },
    { label: 'Directions', value: 'pi pi-directions' },
    { label: 'Directions Alt', value: 'pi pi-directions-alt' },
    { label: 'Discord', value: 'pi pi-discord' },
    { label: 'Dollar', value: 'pi pi-dollar' },
    { label: 'Download', value: 'pi pi-download' },
    { label: 'Eject', value: 'pi pi-eject' },
    { label: 'Ellipsis Horizontal', value: 'pi pi-ellipsis-h' },
    { label: 'Ellipsis Vertical', value: 'pi pi-ellipsis-v' },
    { label: 'Envelope', value: 'pi pi-envelope' },
    { label: 'Eraser', value: 'pi pi-eraser' },
    { label: 'Euro', value: 'pi pi-euro' },
    { label: 'Exclamation Circle', value: 'pi pi-exclamation-circle' },
    { label: 'Exclamation Triangle', value: 'pi pi-exclamation-triangle' },
    { label: 'External Link', value: 'pi pi-external-link' },
    { label: 'Eye', value: 'pi pi-eye' },
    { label: 'Eye Slash', value: 'pi pi-eye-slash' },
    { label: 'Facebook', value: 'pi pi-facebook' },
    { label: 'Fast Backward', value: 'pi pi-fast-backward' },
    { label: 'Fast Forward', value: 'pi pi-fast-forward' },
    { label: 'File', value: 'pi pi-file' },
    { label: 'File Edit', value: 'pi pi-file-edit' },
    { label: 'File Import', value: 'pi pi-file-import' },
    { label: 'File PDF', value: 'pi pi-file-pdf' },
    { label: 'File Excel', value: 'pi pi-file-excel' },
    { label: 'File Export', value: 'pi pi-file-export' },
    { label: 'File Word', value: 'pi pi-file-word' },
    { label: 'Filter', value: 'pi pi-filter' },
    { label: 'Filter Fill', value: 'pi pi-filter-fill' },
    { label: 'Filter Slash', value: 'pi pi-filter-slash' },
    { label: 'Flag', value: 'pi pi-flag' },
    { label: 'Flag Fill', value: 'pi pi-flag-fill' },
    { label: 'Folder', value: 'pi pi-folder' },
    { label: 'Folder Open', value: 'pi pi-folder-open' },
    { label: 'Forward', value: 'pi pi-forward' },
    { label: 'Gift', value: 'pi pi-gift' },
    { label: 'GitHub', value: 'pi pi-github' },
    { label: 'Globe', value: 'pi pi-globe' },
    { label: 'Google', value: 'pi pi-google' },
    { label: 'Hashtag', value: 'pi pi-hashtag' },
    { label: 'Heart', value: 'pi pi-heart' },
    { label: 'Heart Fill', value: 'pi pi-heart-fill' },
    { label: 'History', value: 'pi pi-history' },
    { label: 'Home', value: 'pi pi-home' },
    { label: 'Hourglass', value: 'pi pi-hourglass' },
    { label: 'ID Card', value: 'pi pi-id-card' },
    { label: 'Image', value: 'pi pi-image' },
    { label: 'Images', value: 'pi pi-images' },
    { label: 'Inbox', value: 'pi pi-inbox' },
    { label: 'Info', value: 'pi pi-info' },
    { label: 'Info Circle', value: 'pi pi-info-circle' },
    { label: 'Instagram', value: 'pi pi-instagram' },
    { label: 'Key', value: 'pi pi-key' },
    { label: 'Language', value: 'pi pi-language' },
    { label: 'Link', value: 'pi pi-link' },
    { label: 'LinkedIn', value: 'pi pi-linkedin' },
    { label: 'List', value: 'pi pi-list' },
    { label: 'Lock', value: 'pi pi-lock' },
    { label: 'Lock Open', value: 'pi pi-lock-open' },
    { label: 'Map', value: 'pi pi-map' },
    { label: 'Map Marker', value: 'pi pi-map-marker' },
    { label: 'Megaphone', value: 'pi pi-megaphone' },
    { label: 'Microphone', value: 'pi pi-microphone' },
    { label: 'Microsoft', value: 'pi pi-microsoft' },
    { label: 'Minus', value: 'pi pi-minus' },
    { label: 'Minus Circle', value: 'pi pi-minus-circle' },
    { label: 'Mobile', value: 'pi pi-mobile' },
    { label: 'Money Bill', value: 'pi pi-money-bill' },
    { label: 'Moon', value: 'pi pi-moon' },
    { label: 'Palette', value: 'pi pi-palette' },
    { label: 'Paperclip', value: 'pi pi-paperclip' },
    { label: 'Pause', value: 'pi pi-pause' },
    { label: 'Paypal', value: 'pi pi-paypal' },
    { label: 'Pencil', value: 'pi pi-pencil' },
    { label: 'Percentage', value: 'pi pi-percentage' },
    { label: 'Phone', value: 'pi pi-phone' },
    { label: 'Play', value: 'pi pi-play' },
    { label: 'Plus', value: 'pi pi-plus' },
    { label: 'Plus Circle', value: 'pi pi-plus-circle' },
    { label: 'Pound', value: 'pi pi-pound' },
    { label: 'Power Off', value: 'pi pi-power-off' },
    { label: 'Prime', value: 'pi pi-prime' },
    { label: 'Print', value: 'pi pi-print' },
    { label: 'QR Code', value: 'pi pi-qrcode' },
    { label: 'Question', value: 'pi pi-question' },
    { label: 'Question Circle', value: 'pi pi-question-circle' },
    { label: 'Reddit', value: 'pi pi-reddit' },
    { label: 'Refresh', value: 'pi pi-refresh' },
    { label: 'Replay', value: 'pi pi-replay' },
    { label: 'Reply', value: 'pi pi-reply' },
    { label: 'Save', value: 'pi pi-save' },
    { label: 'Search', value: 'pi pi-search' },
    { label: 'Search Minus', value: 'pi pi-search-minus' },
    { label: 'Search Plus', value: 'pi pi-search-plus' },
    { label: 'Send', value: 'pi pi-send' },
    { label: 'Server', value: 'pi pi-server' },
    { label: 'Share Alt', value: 'pi pi-share-alt' },
    { label: 'Shield', value: 'pi pi-shield' },
    { label: 'Shopping Bag', value: 'pi pi-shopping-bag' },
    { label: 'Shopping Cart', value: 'pi pi-shopping-cart' },
    { label: 'Sign In', value: 'pi pi-sign-in' },
    { label: 'Sign Out', value: 'pi pi-sign-out' },
    { label: 'Sitemap', value: 'pi pi-sitemap' },
    { label: 'Slack', value: 'pi pi-slack' },
    { label: 'Sliders Horizontal', value: 'pi pi-sliders-h' },
    { label: 'Sliders Vertical', value: 'pi pi-sliders-v' },
    { label: 'Sort', value: 'pi pi-sort' },
    { label: 'Sort Alpha Down', value: 'pi pi-sort-alpha-down' },
    { label: 'Sort Alpha Alt Down', value: 'pi pi-sort-alpha-alt-down' },
    { label: 'Sort Alpha Up', value: 'pi pi-sort-alpha-up' },
    { label: 'Sort Alpha Alt Up', value: 'pi pi-sort-alpha-alt-up' },
    { label: 'Sort Alt', value: 'pi pi-sort-alt' },
    { label: 'Sort Alt Slash', value: 'pi pi-sort-slash' },
    { label: 'Sort Amount Down', value: 'pi pi-sort-amount-down' },
    { label: 'Sort Amount Down Alt', value: 'pi pi-sort-amount-down-alt' },
    { label: 'Sort Amount Up', value: 'pi pi-sort-amount-up' },
    { label: 'Sort Amount Up Alt', value: 'pi pi-sort-amount-up-alt' },
    { label: 'Sort Down', value: 'pi pi-sort-down' },
    { label: 'Sort Numeric Down', value: 'pi pi-sort-numeric-down' },
    { label: 'Sort Numeric Alt Down', value: 'pi pi-sort-numeric-alt-down' },
    { label: 'Sort Numeric Up', value: 'pi pi-sort-numeric-up' },
    { label: 'Sort Numeric Alt Up', value: 'pi pi-sort-numeric-alt-up' },
    { label: 'Sort Up', value: 'pi pi-sort-up' },
    { label: 'Spinner', value: 'pi pi-spinner' },
    { label: 'Star', value: 'pi pi-star' },
    { label: 'Star Fill', value: 'pi pi-star-fill' },
    { label: 'Step Backward', value: 'pi pi-step-backward' },
    { label: 'Step Backward Alt', value: 'pi pi-step-backward-alt' },
    { label: 'Step Forward', value: 'pi pi-step-forward' },
    { label: 'Step Forward Alt', value: 'pi pi-step-forward-alt' },
    { label: 'Stop', value: 'pi pi-stop' },
    { label: 'Stop Circle', value: 'pi pi-stop-circle' },
    { label: 'Stopwatch', value: 'pi pi-stopwatch' },
    { label: 'Sun', value: 'pi pi-sun' },
    { label: 'Sync', value: 'pi pi-sync' },
    { label: 'Table', value: 'pi pi-table' },
    { label: 'Tablet', value: 'pi pi-tablet' },
    { label: 'Tag', value: 'pi pi-tag' },
    { label: 'Tags', value: 'pi pi-tags' },
    { label: 'Telegram', value: 'pi pi-telegram' },
    { label: 'Th Large', value: 'pi pi-th-large' },
    { label: 'Thumbs Down', value: 'pi pi-thumbs-down' },
    { label: 'Thumbs Down Fill', value: 'pi pi-thumbs-down-fill' },
    { label: 'Thumbs Up', value: 'pi pi-thumbs-up' },
    { label: 'Thumbs Up Fill', value: 'pi pi-thumbs-up-fill' },
    { label: 'Ticket', value: 'pi pi-ticket' },
    { label: 'Times', value: 'pi pi-times' },
    { label: 'Times Circle', value: 'pi pi-times-circle' },
    { label: 'Trash', value: 'pi pi-trash' },
    { label: 'Truck', value: 'pi pi-truck' },
    { label: 'Twitter', value: 'pi pi-twitter' },
    { label: 'Undo', value: 'pi pi-undo' },
    { label: 'Unlock', value: 'pi pi-unlock' },
    { label: 'Upload', value: 'pi pi-upload' },
    { label: 'User', value: 'pi pi-user' },
    { label: 'User Edit', value: 'pi pi-user-edit' },
    { label: 'User Minus', value: 'pi pi-user-minus' },
    { label: 'User Plus', value: 'pi pi-user-plus' },
    { label: 'Users', value: 'pi pi-users' },
    { label: 'Verified', value: 'pi pi-verified' },
    { label: 'Video', value: 'pi pi-video' },
    { label: 'Vimeo', value: 'pi pi-vimeo' },
    { label: 'Volume Down', value: 'pi pi-volume-down' },
    { label: 'Volume Off', value: 'pi pi-volume-off' },
    { label: 'Volume Up', value: 'pi pi-volume-up' },
    { label: 'Wallet', value: 'pi pi-wallet' },
    { label: 'WhatsApp', value: 'pi pi-whatsapp' },
    { label: 'WiFi', value: 'pi pi-wifi' },
    { label: 'Window Maximize', value: 'pi pi-window-maximize' },
    { label: 'Window Minimize', value: 'pi pi-window-minimize' },
    { label: 'Wrench', value: 'pi pi-wrench' },
    { label: 'YouTube', value: 'pi pi-youtube' }
  
  ];

}


